from typing import Protocol

from app.schemas.stored_content_safety_job import StoredContentSafetyJob


class ContentSafetyJobStore(Protocol):
    def enqueue(self, ticket_id: str, generation: int, now: int) -> StoredContentSafetyJob: ...
    def get(self, job_id: str) -> StoredContentSafetyJob | None: ...
    def claim_next(self, *, now: int, claim_ttl_seconds: int) -> StoredContentSafetyJob | None: ...
    def succeed(self, job_id: str, claim_token: str, now: int) -> bool: ...
    def retry(
        self, job_id: str, claim_token: str, *, available_at: int, now: int, reason: str
    ) -> bool: ...
    def dead_letter(self, job_id: str, claim_token: str, *, now: int, reason: str) -> bool: ...
    def recover_stale(self, *, now: int) -> list[StoredContentSafetyJob]: ...
    def list(self) -> list[StoredContentSafetyJob]: ...
    def clear(self) -> None: ...
