from typing import Protocol

from app.schemas.stored_ticket import StoredTicket
from app.schemas.ticket_response import TicketStatus


class TicketStore(Protocol):
    def next_sequence(self) -> int: ...

    def save(self, ticket: StoredTicket) -> None: ...

    def get(self, ticket_id: str) -> StoredTicket | None: ...

    def list(self) -> list[StoredTicket]: ...

    def update_status(
        self,
        ticket_id: str,
        status: TicketStatus,
        updated_at: str,
    ) -> StoredTicket | None: ...

    def has_ticket_id(self, ticket_id: str) -> bool: ...

    def has_ticket_number(self, ticket_number: str) -> bool: ...

    def has_tracking_code(self, tracking_code: str) -> bool: ...

    def clear(self) -> None: ...
