from typing import Protocol

from app.schemas.stored_ticket import StoredTicket


class TicketStore(Protocol):
    def next_sequence(self) -> int: ...

    def save(self, ticket: StoredTicket) -> None: ...

    def get(self, ticket_id: str) -> StoredTicket | None: ...

    def list(self) -> list[StoredTicket]: ...

    def has_ticket_id(self, ticket_id: str) -> bool: ...

    def has_ticket_number(self, ticket_number: str) -> bool: ...

    def has_tracking_code(self, tracking_code: str) -> bool: ...

    def clear(self) -> None: ...
